/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.problems;

public class App {

    public static void main(String[] args) {
        /* Leetcode Easy */
//        TwoSum.main();
//        PalindromeNumber.main();
//        RomanToInt.main();
//        ValidParentheses.main();
//        RunningSumOf1DArray.main();

        /* Leetcode Medium */
//        AddTwoNumbers.main();
//        ContainerWithMostWater.main();
//        ThreeSum.main();
//        LengthOfLongestSubstring.main();

        /* Leetcode Hard */

        /* Other */
//        TargetSubset.main();
    }
}
