/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.problems;

public class App {

    public static void main(String[] args) {
//        TargetSubset.main();
//        ContainerWithMostWater.main();
        ThreeSum.main();
    }
}
